# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T10:37:00+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, List, Optional

from pydantic import BaseModel, Field, RootModel, SecretStr


class AccessDeniedFault(RootModel[Any]):
    root: Any


class AddTagsToResourceResponse(BaseModel):
    pass


class AuthMechanismValue(Enum):
    default = 'default'
    mongodb_cr = 'mongodb_cr'
    scram_sha_1 = 'scram_sha_1'


class AuthTypeValue(Enum):
    no = 'no'
    password = 'password'


class Boolean(RootModel[bool]):
    root: bool


class BooleanOptional(RootModel[bool]):
    root: bool


class CannedAclForObjectsValue(Enum):
    none = 'none'
    private = 'private'
    public_read = 'public-read'
    public_read_write = 'public-read-write'
    authenticated_read = 'authenticated-read'
    aws_exec_read = 'aws-exec-read'
    bucket_owner_read = 'bucket-owner-read'
    bucket_owner_full_control = 'bucket-owner-full-control'


class CertificateWallet(RootModel[str]):
    root: str


class CharLengthSemantics(Enum):
    default = 'default'
    char = 'char'
    byte = 'byte'


class CollectorNotFoundFault(RootModel[Any]):
    root: Any


class CollectorStatus(Enum):
    UNREGISTERED = 'UNREGISTERED'
    ACTIVE = 'ACTIVE'


class CompressionTypeValue(Enum):
    none = 'none'
    gzip = 'gzip'


class DataFormatValue(Enum):
    csv = 'csv'
    parquet = 'parquet'


class DatePartitionDelimiterValue(Enum):
    SLASH = 'SLASH'
    UNDERSCORE = 'UNDERSCORE'
    DASH = 'DASH'
    NONE = 'NONE'


class DatePartitionSequenceValue(Enum):
    YYYYMMDD = 'YYYYMMDD'
    YYYYMMDDHH = 'YYYYMMDDHH'
    YYYYMM = 'YYYYMM'
    MMYYYYDD = 'MMYYYYDD'
    DDMMYYYY = 'DDMMYYYY'


class DeleteReplicationSubnetGroupResponse(BaseModel):
    pass


class DescribeAccountAttributesMessage(BaseModel):
    pass


class DmsSslModeValue(Enum):
    none = 'none'
    require = 'require'
    verify_ca = 'verify-ca'
    verify_full = 'verify-full'


class DoubleOptional(RootModel[float]):
    root: float


class EncodingTypeValue(Enum):
    plain = 'plain'
    plain_dictionary = 'plain-dictionary'
    rle_dictionary = 'rle-dictionary'


class EncryptionModeValue(Enum):
    sse_s3 = 'sse-s3'
    sse_kms = 'sse-kms'


class EndpointSettingTypeValue(Enum):
    string = 'string'
    boolean = 'boolean'
    integer = 'integer'
    enum = 'enum'


class InsufficientResourceCapacityFault(RootModel[Any]):
    root: Any


class Integer(RootModel[int]):
    root: int


class IntegerList(RootModel[List[Integer]]):
    root: List[Integer]


class IntegerOptional(RootModel[int]):
    root: int


class InvalidCertificateFault(RootModel[Any]):
    root: Any


class InvalidOperationFault(RootModel[Any]):
    root: Any


class InvalidResourceStateFault(RootModel[Any]):
    root: Any


class InvalidSubnet(RootModel[Any]):
    root: Any


class InventoryData(BaseModel):
    NumberOfDatabases: Optional[IntegerOptional] = None
    NumberOfSchemas: Optional[IntegerOptional] = None


class KMSAccessDeniedFault(RootModel[Any]):
    root: Any


class KMSDisabledFault(RootModel[Any]):
    root: Any


class KMSFault(RootModel[Any]):
    root: Any


class KMSInvalidStateFault(RootModel[Any]):
    root: Any


class KMSKeyNotAccessibleFault(RootModel[Any]):
    root: Any


class KMSNotFoundFault(RootModel[Any]):
    root: Any


class KMSThrottlingFault(RootModel[Any]):
    root: Any


class KafkaSaslMechanism(Enum):
    scram_sha_512 = 'scram-sha-512'
    plain = 'plain'


class KafkaSecurityProtocol(Enum):
    plaintext = 'plaintext'
    ssl_authentication = 'ssl-authentication'
    ssl_encryption = 'ssl-encryption'
    sasl_ssl = 'sasl-ssl'


class Long(RootModel[int]):
    root: int


class LongOptional(RootModel[int]):
    root: int


class MessageFormatValue(Enum):
    json = 'json'
    json_unformatted = 'json-unformatted'


class MigrationTypeValue(Enum):
    full_load = 'full-load'
    cdc = 'cdc'
    full_load_and_cdc = 'full-load-and-cdc'


class NestingLevelValue(Enum):
    none = 'none'
    one = 'one'


class ParquetVersionValue(Enum):
    parquet_1_0 = 'parquet-1-0'
    parquet_2_0 = 'parquet-2-0'


class PluginNameValue(Enum):
    no_preference = 'no-preference'
    test_decoding = 'test-decoding'
    pglogical = 'pglogical'


class RedisAuthTypeValue(Enum):
    none = 'none'
    auth_role = 'auth-role'
    auth_token = 'auth-token'


class RefreshSchemasStatusTypeValue(Enum):
    successful = 'successful'
    failed = 'failed'
    refreshing = 'refreshing'


class ReleaseStatusValues(Enum):
    beta = 'beta'
    prod = 'prod'


class ReloadOptionValue(Enum):
    data_reload = 'data-reload'
    validate_only = 'validate-only'


class RemoveTagsFromResourceResponse(BaseModel):
    pass


class ReplicationEndpointTypeValue(Enum):
    source = 'source'
    target = 'target'


class ReplicationSubnetGroupDoesNotCoverEnoughAZs(RootModel[Any]):
    root: Any


class ReplicationTaskAssessmentRunProgress(BaseModel):
    IndividualAssessmentCompletedCount: Optional[Integer] = None
    IndividualAssessmentCount: Optional[Integer] = None


class ResourceAlreadyExistsFault(RootModel[Any]):
    root: Any


class ResourceNotFoundFault(RootModel[Any]):
    root: Any


class ResourceQuotaExceededFault(RootModel[Any]):
    root: Any


class S3AccessDeniedFault(RootModel[Any]):
    root: Any


class S3ResourceNotFoundFault(RootModel[Any]):
    root: Any


class SNSInvalidTopicFault(RootModel[Any]):
    root: Any


class SNSNoAuthorizationFault(RootModel[Any]):
    root: Any


class SafeguardPolicy(Enum):
    rely_on_sql_server_replication_agent = 'rely-on-sql-server-replication-agent'
    exclusive_automatic_truncation = 'exclusive-automatic-truncation'
    shared_automatic_truncation = 'shared-automatic-truncation'


class SecretString(RootModel[SecretStr]):
    root: SecretStr


class SourceType(Enum):
    replication_instance = 'replication-instance'


class SslSecurityProtocolValue(Enum):
    plaintext = 'plaintext'
    ssl_encryption = 'ssl-encryption'


class StartReplicationTaskTypeValue(Enum):
    start_replication = 'start-replication'
    resume_processing = 'resume-processing'
    reload_target = 'reload-target'


class StorageQuotaExceededFault(RootModel[Any]):
    root: Any


class String(RootModel[str]):
    root: str


class StringList(RootModel[List[String]]):
    root: List[String]


class SubnetAlreadyInUse(RootModel[Any]):
    root: Any


class SubnetIdentifierList(RootModel[List[String]]):
    root: List[String]


class SupportedEndpointType(BaseModel):
    EndpointType: Optional[ReplicationEndpointTypeValue] = None
    EngineDisplayName: Optional[String] = None
    EngineName: Optional[String] = None
    ReplicationInstanceEngineMinimumVersion: Optional[String] = None
    SupportsCDC: Optional[Boolean] = None


class SupportedEndpointTypeList(RootModel[List[SupportedEndpointType]]):
    root: List[SupportedEndpointType]


class SybaseSettings(BaseModel):
    DatabaseName: Optional[String] = None
    Password: Optional[SecretString] = None
    Port: Optional[IntegerOptional] = None
    SecretsManagerAccessRoleArn: Optional[String] = None
    SecretsManagerSecretId: Optional[String] = None
    ServerName: Optional[String] = None
    Username: Optional[String] = None


class TStamp(RootModel[datetime]):
    root: datetime


class TableStatistics(BaseModel):
    AppliedDdls: Optional[LongOptional] = None
    AppliedDeletes: Optional[LongOptional] = None
    AppliedInserts: Optional[LongOptional] = None
    AppliedUpdates: Optional[LongOptional] = None
    Ddls: Optional[Long] = None
    Deletes: Optional[Long] = None
    FullLoadCondtnlChkFailedRows: Optional[Long] = None
    FullLoadEndTime: Optional[TStamp] = None
    FullLoadErrorRows: Optional[Long] = None
    FullLoadReloaded: Optional[BooleanOptional] = None
    FullLoadRows: Optional[Long] = None
    FullLoadStartTime: Optional[TStamp] = None
    Inserts: Optional[Long] = None
    LastUpdateTime: Optional[TStamp] = None
    SchemaName: Optional[String] = None
    TableName: Optional[String] = None
    TableState: Optional[String] = None
    Updates: Optional[Long] = None
    ValidationFailedRecords: Optional[Long] = None
    ValidationPendingRecords: Optional[Long] = None
    ValidationState: Optional[String] = None
    ValidationStateDetails: Optional[String] = None
    ValidationSuspendedRecords: Optional[Long] = None


class TableStatisticsList(RootModel[List[TableStatistics]]):
    root: List[TableStatistics]


class TableToReload(BaseModel):
    SchemaName: String
    TableName: String


class Tag(BaseModel):
    Key: Optional[String] = None
    ResourceArn: Optional[String] = None
    Value: Optional[String] = None


class TagList(RootModel[List[Tag]]):
    root: List[Tag]


class TargetDbType(Enum):
    specific_database = 'specific-database'
    multiple_databases = 'multiple-databases'


class TestConnectionMessage(BaseModel):
    EndpointArn: String
    ReplicationInstanceArn: String


class TlogAccessMode(Enum):
    BackupOnly = 'BackupOnly'
    PreferBackup = 'PreferBackup'
    PreferTlog = 'PreferTlog'
    TlogOnly = 'TlogOnly'


class UpdateSubscriptionsToEventBridgeMessage(BaseModel):
    ForceMove: Optional[BooleanOptional] = None


class UpdateSubscriptionsToEventBridgeResponse(BaseModel):
    Result: Optional[String] = None


class UpgradeDependencyFailureFault(RootModel[Any]):
    root: Any


class VersionStatus(Enum):
    UP_TO_DATE = 'UP_TO_DATE'
    OUTDATED = 'OUTDATED'
    UNSUPPORTED = 'UNSUPPORTED'


class VpcSecurityGroupIdList(RootModel[List[String]]):
    root: List[String]


class VpcSecurityGroupMembership(BaseModel):
    Status: Optional[String] = None
    VpcSecurityGroupId: Optional[String] = None


class VpcSecurityGroupMembershipList(RootModel[List[VpcSecurityGroupMembership]]):
    root: List[VpcSecurityGroupMembership]


class XAmzTarget(Enum):
    AmazonDMSv20160101_AddTagsToResource = 'AmazonDMSv20160101.AddTagsToResource'


class XAmzTarget1(Enum):
    AmazonDMSv20160101_ApplyPendingMaintenanceAction = (
        'AmazonDMSv20160101.ApplyPendingMaintenanceAction'
    )


class XAmzTarget2(Enum):
    AmazonDMSv20160101_BatchStartRecommendations = (
        'AmazonDMSv20160101.BatchStartRecommendations'
    )


class XAmzTarget3(Enum):
    AmazonDMSv20160101_CancelReplicationTaskAssessmentRun = (
        'AmazonDMSv20160101.CancelReplicationTaskAssessmentRun'
    )


class XAmzTarget4(Enum):
    AmazonDMSv20160101_CreateEndpoint = 'AmazonDMSv20160101.CreateEndpoint'


class XAmzTarget5(Enum):
    AmazonDMSv20160101_CreateEventSubscription = (
        'AmazonDMSv20160101.CreateEventSubscription'
    )


class XAmzTarget6(Enum):
    AmazonDMSv20160101_CreateFleetAdvisorCollector = (
        'AmazonDMSv20160101.CreateFleetAdvisorCollector'
    )


class XAmzTarget7(Enum):
    AmazonDMSv20160101_CreateReplicationInstance = (
        'AmazonDMSv20160101.CreateReplicationInstance'
    )


class XAmzTarget8(Enum):
    AmazonDMSv20160101_CreateReplicationSubnetGroup = (
        'AmazonDMSv20160101.CreateReplicationSubnetGroup'
    )


class XAmzTarget9(Enum):
    AmazonDMSv20160101_CreateReplicationTask = (
        'AmazonDMSv20160101.CreateReplicationTask'
    )


class XAmzTarget10(Enum):
    AmazonDMSv20160101_DeleteCertificate = 'AmazonDMSv20160101.DeleteCertificate'


class XAmzTarget11(Enum):
    AmazonDMSv20160101_DeleteConnection = 'AmazonDMSv20160101.DeleteConnection'


class XAmzTarget12(Enum):
    AmazonDMSv20160101_DeleteEndpoint = 'AmazonDMSv20160101.DeleteEndpoint'


class XAmzTarget13(Enum):
    AmazonDMSv20160101_DeleteEventSubscription = (
        'AmazonDMSv20160101.DeleteEventSubscription'
    )


class XAmzTarget14(Enum):
    AmazonDMSv20160101_DeleteFleetAdvisorCollector = (
        'AmazonDMSv20160101.DeleteFleetAdvisorCollector'
    )


class XAmzTarget15(Enum):
    AmazonDMSv20160101_DeleteFleetAdvisorDatabases = (
        'AmazonDMSv20160101.DeleteFleetAdvisorDatabases'
    )


class XAmzTarget16(Enum):
    AmazonDMSv20160101_DeleteReplicationInstance = (
        'AmazonDMSv20160101.DeleteReplicationInstance'
    )


class XAmzTarget17(Enum):
    AmazonDMSv20160101_DeleteReplicationSubnetGroup = (
        'AmazonDMSv20160101.DeleteReplicationSubnetGroup'
    )


class XAmzTarget18(Enum):
    AmazonDMSv20160101_DeleteReplicationTask = (
        'AmazonDMSv20160101.DeleteReplicationTask'
    )


class XAmzTarget19(Enum):
    AmazonDMSv20160101_DeleteReplicationTaskAssessmentRun = (
        'AmazonDMSv20160101.DeleteReplicationTaskAssessmentRun'
    )


class XAmzTarget20(Enum):
    AmazonDMSv20160101_DescribeAccountAttributes = (
        'AmazonDMSv20160101.DescribeAccountAttributes'
    )


class XAmzTarget21(Enum):
    AmazonDMSv20160101_DescribeApplicableIndividualAssessments = (
        'AmazonDMSv20160101.DescribeApplicableIndividualAssessments'
    )


class XAmzTarget22(Enum):
    AmazonDMSv20160101_DescribeCertificates = 'AmazonDMSv20160101.DescribeCertificates'


class XAmzTarget23(Enum):
    AmazonDMSv20160101_DescribeConnections = 'AmazonDMSv20160101.DescribeConnections'


class XAmzTarget24(Enum):
    AmazonDMSv20160101_DescribeEndpointSettings = (
        'AmazonDMSv20160101.DescribeEndpointSettings'
    )


class XAmzTarget25(Enum):
    AmazonDMSv20160101_DescribeEndpointTypes = (
        'AmazonDMSv20160101.DescribeEndpointTypes'
    )


class XAmzTarget26(Enum):
    AmazonDMSv20160101_DescribeEndpoints = 'AmazonDMSv20160101.DescribeEndpoints'


class XAmzTarget27(Enum):
    AmazonDMSv20160101_DescribeEventCategories = (
        'AmazonDMSv20160101.DescribeEventCategories'
    )


class XAmzTarget28(Enum):
    AmazonDMSv20160101_DescribeEventSubscriptions = (
        'AmazonDMSv20160101.DescribeEventSubscriptions'
    )


class XAmzTarget29(Enum):
    AmazonDMSv20160101_DescribeEvents = 'AmazonDMSv20160101.DescribeEvents'


class XAmzTarget30(Enum):
    AmazonDMSv20160101_DescribeFleetAdvisorCollectors = (
        'AmazonDMSv20160101.DescribeFleetAdvisorCollectors'
    )


class XAmzTarget31(Enum):
    AmazonDMSv20160101_DescribeFleetAdvisorDatabases = (
        'AmazonDMSv20160101.DescribeFleetAdvisorDatabases'
    )


class XAmzTarget32(Enum):
    AmazonDMSv20160101_DescribeFleetAdvisorLsaAnalysis = (
        'AmazonDMSv20160101.DescribeFleetAdvisorLsaAnalysis'
    )


class XAmzTarget33(Enum):
    AmazonDMSv20160101_DescribeFleetAdvisorSchemaObjectSummary = (
        'AmazonDMSv20160101.DescribeFleetAdvisorSchemaObjectSummary'
    )


class XAmzTarget34(Enum):
    AmazonDMSv20160101_DescribeFleetAdvisorSchemas = (
        'AmazonDMSv20160101.DescribeFleetAdvisorSchemas'
    )


class XAmzTarget35(Enum):
    AmazonDMSv20160101_DescribeOrderableReplicationInstances = (
        'AmazonDMSv20160101.DescribeOrderableReplicationInstances'
    )


class XAmzTarget36(Enum):
    AmazonDMSv20160101_DescribePendingMaintenanceActions = (
        'AmazonDMSv20160101.DescribePendingMaintenanceActions'
    )


class XAmzTarget37(Enum):
    AmazonDMSv20160101_DescribeRecommendationLimitations = (
        'AmazonDMSv20160101.DescribeRecommendationLimitations'
    )


class XAmzTarget38(Enum):
    AmazonDMSv20160101_DescribeRecommendations = (
        'AmazonDMSv20160101.DescribeRecommendations'
    )


class XAmzTarget39(Enum):
    AmazonDMSv20160101_DescribeRefreshSchemasStatus = (
        'AmazonDMSv20160101.DescribeRefreshSchemasStatus'
    )


class XAmzTarget40(Enum):
    AmazonDMSv20160101_DescribeReplicationInstanceTaskLogs = (
        'AmazonDMSv20160101.DescribeReplicationInstanceTaskLogs'
    )


class XAmzTarget41(Enum):
    AmazonDMSv20160101_DescribeReplicationInstances = (
        'AmazonDMSv20160101.DescribeReplicationInstances'
    )


class XAmzTarget42(Enum):
    AmazonDMSv20160101_DescribeReplicationSubnetGroups = (
        'AmazonDMSv20160101.DescribeReplicationSubnetGroups'
    )


class XAmzTarget43(Enum):
    AmazonDMSv20160101_DescribeReplicationTaskAssessmentResults = (
        'AmazonDMSv20160101.DescribeReplicationTaskAssessmentResults'
    )


class XAmzTarget44(Enum):
    AmazonDMSv20160101_DescribeReplicationTaskAssessmentRuns = (
        'AmazonDMSv20160101.DescribeReplicationTaskAssessmentRuns'
    )


class XAmzTarget45(Enum):
    AmazonDMSv20160101_DescribeReplicationTaskIndividualAssessments = (
        'AmazonDMSv20160101.DescribeReplicationTaskIndividualAssessments'
    )


class XAmzTarget46(Enum):
    AmazonDMSv20160101_DescribeReplicationTasks = (
        'AmazonDMSv20160101.DescribeReplicationTasks'
    )


class XAmzTarget47(Enum):
    AmazonDMSv20160101_DescribeSchemas = 'AmazonDMSv20160101.DescribeSchemas'


class XAmzTarget48(Enum):
    AmazonDMSv20160101_DescribeTableStatistics = (
        'AmazonDMSv20160101.DescribeTableStatistics'
    )


class XAmzTarget49(Enum):
    AmazonDMSv20160101_ImportCertificate = 'AmazonDMSv20160101.ImportCertificate'


class XAmzTarget50(Enum):
    AmazonDMSv20160101_ListTagsForResource = 'AmazonDMSv20160101.ListTagsForResource'


class XAmzTarget51(Enum):
    AmazonDMSv20160101_ModifyEndpoint = 'AmazonDMSv20160101.ModifyEndpoint'


class XAmzTarget52(Enum):
    AmazonDMSv20160101_ModifyEventSubscription = (
        'AmazonDMSv20160101.ModifyEventSubscription'
    )


class XAmzTarget53(Enum):
    AmazonDMSv20160101_ModifyReplicationInstance = (
        'AmazonDMSv20160101.ModifyReplicationInstance'
    )


class XAmzTarget54(Enum):
    AmazonDMSv20160101_ModifyReplicationSubnetGroup = (
        'AmazonDMSv20160101.ModifyReplicationSubnetGroup'
    )


class XAmzTarget55(Enum):
    AmazonDMSv20160101_ModifyReplicationTask = (
        'AmazonDMSv20160101.ModifyReplicationTask'
    )


class XAmzTarget56(Enum):
    AmazonDMSv20160101_MoveReplicationTask = 'AmazonDMSv20160101.MoveReplicationTask'


class XAmzTarget57(Enum):
    AmazonDMSv20160101_RebootReplicationInstance = (
        'AmazonDMSv20160101.RebootReplicationInstance'
    )


class XAmzTarget58(Enum):
    AmazonDMSv20160101_RefreshSchemas = 'AmazonDMSv20160101.RefreshSchemas'


class XAmzTarget59(Enum):
    AmazonDMSv20160101_ReloadTables = 'AmazonDMSv20160101.ReloadTables'


class XAmzTarget60(Enum):
    AmazonDMSv20160101_RemoveTagsFromResource = (
        'AmazonDMSv20160101.RemoveTagsFromResource'
    )


class XAmzTarget61(Enum):
    AmazonDMSv20160101_RunFleetAdvisorLsaAnalysis = (
        'AmazonDMSv20160101.RunFleetAdvisorLsaAnalysis'
    )


class XAmzTarget62(Enum):
    AmazonDMSv20160101_StartRecommendations = 'AmazonDMSv20160101.StartRecommendations'


class XAmzTarget63(Enum):
    AmazonDMSv20160101_StartReplicationTask = 'AmazonDMSv20160101.StartReplicationTask'


class XAmzTarget64(Enum):
    AmazonDMSv20160101_StartReplicationTaskAssessment = (
        'AmazonDMSv20160101.StartReplicationTaskAssessment'
    )


class XAmzTarget65(Enum):
    AmazonDMSv20160101_StartReplicationTaskAssessmentRun = (
        'AmazonDMSv20160101.StartReplicationTaskAssessmentRun'
    )


class XAmzTarget66(Enum):
    AmazonDMSv20160101_StopReplicationTask = 'AmazonDMSv20160101.StopReplicationTask'


class XAmzTarget67(Enum):
    AmazonDMSv20160101_TestConnection = 'AmazonDMSv20160101.TestConnection'


class XAmzTarget68(Enum):
    AmazonDMSv20160101_UpdateSubscriptionsToEventBridge = (
        'AmazonDMSv20160101.UpdateSubscriptionsToEventBridge'
    )


class AccountQuota(BaseModel):
    AccountQuotaName: Optional[String] = None
    Max: Optional[Long] = None
    Used: Optional[Long] = None


class AccountQuotaList(RootModel[List[AccountQuota]]):
    root: List[AccountQuota]


class AddTagsToResourceMessage(BaseModel):
    ResourceArn: String
    Tags: TagList


class ApplyPendingMaintenanceActionMessage(BaseModel):
    ApplyAction: String
    OptInType: String
    ReplicationInstanceArn: String


class ArnList(RootModel[List[String]]):
    root: List[String]


class AvailabilityZone(BaseModel):
    Name: Optional[String] = None


class AvailabilityZonesList(RootModel[List[String]]):
    root: List[String]


class BatchStartRecommendationsErrorEntry(BaseModel):
    Code: Optional[String] = None
    DatabaseId: Optional[String] = None
    Message: Optional[String] = None


class BatchStartRecommendationsErrorEntryList(
    RootModel[List[BatchStartRecommendationsErrorEntry]]
):
    root: List[BatchStartRecommendationsErrorEntry]


class BatchStartRecommendationsResponse(BaseModel):
    ErrorEntries: Optional[BatchStartRecommendationsErrorEntryList] = None


class CancelReplicationTaskAssessmentRunMessage(BaseModel):
    ReplicationTaskAssessmentRunArn: String


class Certificate(BaseModel):
    CertificateArn: Optional[String] = None
    CertificateCreationDate: Optional[TStamp] = None
    CertificateIdentifier: Optional[String] = None
    CertificateOwner: Optional[String] = None
    CertificatePem: Optional[String] = None
    CertificateWallet_1: Optional[CertificateWallet] = Field(
        None, alias='CertificateWallet'
    )
    KeyLength: Optional[IntegerOptional] = None
    SigningAlgorithm: Optional[String] = None
    ValidFromDate: Optional[TStamp] = None
    ValidToDate: Optional[TStamp] = None


class CertificateList(RootModel[List[Certificate]]):
    root: List[Certificate]


class CollectorHealthCheck(BaseModel):
    CollectorStatus_1: Optional[CollectorStatus] = Field(None, alias='CollectorStatus')
    LocalCollectorS3Access: Optional[BooleanOptional] = None
    WebCollectorGrantedRoleBasedAccess: Optional[BooleanOptional] = None
    WebCollectorS3Access: Optional[BooleanOptional] = None


class CollectorResponse(BaseModel):
    CollectorHealthCheck_1: Optional[CollectorHealthCheck] = Field(
        None, alias='CollectorHealthCheck'
    )
    CollectorName: Optional[String] = None
    CollectorReferencedId: Optional[String] = None
    CollectorVersion: Optional[String] = None
    CreatedDate: Optional[String] = None
    Description: Optional[String] = None
    InventoryData_1: Optional[InventoryData] = Field(None, alias='InventoryData')
    LastDataReceived: Optional[String] = None
    ModifiedDate: Optional[String] = None
    RegisteredDate: Optional[String] = None
    S3BucketName: Optional[String] = None
    ServiceAccessRoleArn: Optional[String] = None
    VersionStatus_1: Optional[VersionStatus] = Field(None, alias='VersionStatus')


class CollectorResponses(RootModel[List[CollectorResponse]]):
    root: List[CollectorResponse]


class CollectorShortInfoResponse(BaseModel):
    CollectorName: Optional[String] = None
    CollectorReferencedId: Optional[String] = None


class CollectorsList(RootModel[List[CollectorShortInfoResponse]]):
    root: List[CollectorShortInfoResponse]


class Connection(BaseModel):
    EndpointArn: Optional[String] = None
    EndpointIdentifier: Optional[String] = None
    LastFailureMessage: Optional[String] = None
    ReplicationInstanceArn: Optional[String] = None
    ReplicationInstanceIdentifier: Optional[String] = None
    Status: Optional[String] = None


class ConnectionList(RootModel[List[Connection]]):
    root: List[Connection]


class CreateFleetAdvisorCollectorRequest(BaseModel):
    CollectorName: String
    Description: Optional[String] = None
    S3BucketName: String
    ServiceAccessRoleArn: String


class CreateFleetAdvisorCollectorResponse(BaseModel):
    CollectorName: Optional[String] = None
    CollectorReferencedId: Optional[String] = None
    Description: Optional[String] = None
    S3BucketName: Optional[String] = None
    ServiceAccessRoleArn: Optional[String] = None


class CreateReplicationInstanceMessage(BaseModel):
    AllocatedStorage: Optional[IntegerOptional] = None
    AutoMinorVersionUpgrade: Optional[BooleanOptional] = None
    AvailabilityZone: Optional[String] = None
    DnsNameServers: Optional[String] = None
    EngineVersion: Optional[String] = None
    KmsKeyId: Optional[String] = None
    MultiAZ: Optional[BooleanOptional] = None
    NetworkType: Optional[String] = None
    PreferredMaintenanceWindow: Optional[String] = None
    PubliclyAccessible: Optional[BooleanOptional] = None
    ReplicationInstanceClass: String
    ReplicationInstanceIdentifier: String
    ReplicationSubnetGroupIdentifier: Optional[String] = None
    ResourceIdentifier: Optional[String] = None
    Tags: Optional[TagList] = None
    VpcSecurityGroupIds: Optional[VpcSecurityGroupIdList] = None


class CreateReplicationSubnetGroupMessage(BaseModel):
    ReplicationSubnetGroupDescription: String
    ReplicationSubnetGroupIdentifier: String
    SubnetIds: SubnetIdentifierList
    Tags: Optional[TagList] = None


class CreateReplicationTaskMessage(BaseModel):
    CdcStartPosition: Optional[String] = None
    CdcStartTime: Optional[TStamp] = None
    CdcStopPosition: Optional[String] = None
    MigrationType: MigrationTypeValue
    ReplicationInstanceArn: String
    ReplicationTaskIdentifier: String
    ReplicationTaskSettings: Optional[String] = None
    ResourceIdentifier: Optional[String] = None
    SourceEndpointArn: String
    TableMappings: String
    Tags: Optional[TagList] = None
    TargetEndpointArn: String
    TaskData: Optional[String] = None


class DatabaseInstanceSoftwareDetailsResponse(BaseModel):
    Engine: Optional[String] = None
    EngineEdition: Optional[String] = None
    EngineVersion: Optional[String] = None
    OsArchitecture: Optional[IntegerOptional] = None
    ServicePack: Optional[String] = None
    SupportLevel: Optional[String] = None
    Tooltip: Optional[String] = None


class DatabaseShortInfoResponse(BaseModel):
    DatabaseEngine: Optional[String] = None
    DatabaseId: Optional[String] = None
    DatabaseIpAddress: Optional[String] = None
    DatabaseName: Optional[String] = None


class DeleteCertificateMessage(BaseModel):
    CertificateArn: String


class DeleteCertificateResponse(BaseModel):
    Certificate_1: Optional[Certificate] = Field(None, alias='Certificate')


class DeleteCollectorRequest(BaseModel):
    CollectorReferencedId: String


class DeleteConnectionMessage(BaseModel):
    EndpointArn: String
    ReplicationInstanceArn: String


class DeleteConnectionResponse(BaseModel):
    Connection_1: Optional[Connection] = Field(None, alias='Connection')


class DeleteEndpointMessage(BaseModel):
    EndpointArn: String


class DeleteEventSubscriptionMessage(BaseModel):
    SubscriptionName: String


class DeleteFleetAdvisorDatabasesRequest(BaseModel):
    DatabaseIds: StringList


class DeleteFleetAdvisorDatabasesResponse(BaseModel):
    DatabaseIds: Optional[StringList] = None


class DeleteReplicationInstanceMessage(BaseModel):
    ReplicationInstanceArn: String


class DeleteReplicationSubnetGroupMessage(BaseModel):
    ReplicationSubnetGroupIdentifier: String


class DeleteReplicationTaskAssessmentRunMessage(BaseModel):
    ReplicationTaskAssessmentRunArn: String


class DeleteReplicationTaskMessage(BaseModel):
    ReplicationTaskArn: String


class DescribeAccountAttributesResponse(BaseModel):
    AccountQuotas: Optional[AccountQuotaList] = None
    UniqueAccountIdentifier: Optional[String] = None


class DescribeApplicableIndividualAssessmentsMessage(BaseModel):
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None
    MigrationType: Optional[MigrationTypeValue] = None
    ReplicationInstanceArn: Optional[String] = None
    ReplicationTaskArn: Optional[String] = None
    SourceEngineName: Optional[String] = None
    TargetEngineName: Optional[String] = None


class DescribeCertificatesResponse(BaseModel):
    Certificates: Optional[CertificateList] = None
    Marker: Optional[String] = None


class DescribeConnectionsResponse(BaseModel):
    Connections: Optional[ConnectionList] = None
    Marker: Optional[String] = None


class DescribeEndpointSettingsMessage(BaseModel):
    EngineName: String
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None


class DescribeEndpointTypesResponse(BaseModel):
    Marker: Optional[String] = None
    SupportedEndpointTypes: Optional[SupportedEndpointTypeList] = None


class DescribeFleetAdvisorCollectorsResponse(BaseModel):
    Collectors: Optional[CollectorResponses] = None
    NextToken: Optional[String] = None


class DescribeFleetAdvisorLsaAnalysisRequest(BaseModel):
    MaxRecords: Optional[IntegerOptional] = None
    NextToken: Optional[String] = None


class DescribeOrderableReplicationInstancesMessage(BaseModel):
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None


class DescribeRefreshSchemasStatusMessage(BaseModel):
    EndpointArn: String


class DescribeReplicationInstanceTaskLogsMessage(BaseModel):
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None
    ReplicationInstanceArn: String


class DescribeReplicationTaskAssessmentResultsMessage(BaseModel):
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None
    ReplicationTaskArn: Optional[String] = None


class DescribeSchemasMessage(BaseModel):
    EndpointArn: String
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None


class DescribeTableStatisticsResponse(BaseModel):
    Marker: Optional[String] = None
    ReplicationTaskArn: Optional[String] = None
    TableStatistics: Optional[TableStatisticsList] = None


class DmsTransferSettings(BaseModel):
    BucketName: Optional[String] = None
    ServiceAccessRoleArn: Optional[String] = None


class DocDbSettings(BaseModel):
    DatabaseName: Optional[String] = None
    DocsToInvestigate: Optional[IntegerOptional] = None
    ExtractDocId: Optional[BooleanOptional] = None
    KmsKeyId: Optional[String] = None
    NestingLevel: Optional[NestingLevelValue] = None
    Password: Optional[SecretString] = None
    Port: Optional[IntegerOptional] = None
    SecretsManagerAccessRoleArn: Optional[String] = None
    SecretsManagerSecretId: Optional[String] = None
    ServerName: Optional[String] = None
    Username: Optional[String] = None


class DynamoDbSettings(BaseModel):
    ServiceAccessRoleArn: String


class ElasticsearchSettings(BaseModel):
    EndpointUri: String
    ErrorRetryDuration: Optional[IntegerOptional] = None
    FullLoadErrorPercentage: Optional[IntegerOptional] = None
    ServiceAccessRoleArn: String
    UseNewMappingType: Optional[BooleanOptional] = None


class EndpointSettingEnumValues(RootModel[List[String]]):
    root: List[String]


class EventCategoriesList(RootModel[List[String]]):
    root: List[String]


class EventCategoryGroup(BaseModel):
    EventCategories: Optional[EventCategoriesList] = None
    SourceType: Optional[String] = None


class EventCategoryGroupList(RootModel[List[EventCategoryGroup]]):
    root: List[EventCategoryGroup]


class ExcludeTestList(RootModel[List[String]]):
    root: List[String]


class FilterValueList(RootModel[List[String]]):
    root: List[String]


class FleetAdvisorLsaAnalysisResponse(BaseModel):
    LsaAnalysisId: Optional[String] = None
    Status: Optional[String] = None


class FleetAdvisorLsaAnalysisResponseList(
    RootModel[List[FleetAdvisorLsaAnalysisResponse]]
):
    root: List[FleetAdvisorLsaAnalysisResponse]


class FleetAdvisorSchemaObjectResponse(BaseModel):
    CodeLineCount: Optional[LongOptional] = None
    CodeSize: Optional[LongOptional] = None
    NumberOfObjects: Optional[LongOptional] = None
    ObjectType: Optional[String] = None
    SchemaId: Optional[String] = None


class GcpMySQLSettings(BaseModel):
    AfterConnectScript: Optional[String] = None
    CleanSourceMetadataOnMismatch: Optional[BooleanOptional] = None
    DatabaseName: Optional[String] = None
    EventsPollInterval: Optional[IntegerOptional] = None
    MaxFileSize: Optional[IntegerOptional] = None
    ParallelLoadThreads: Optional[IntegerOptional] = None
    Password: Optional[SecretString] = None
    Port: Optional[IntegerOptional] = None
    SecretsManagerAccessRoleArn: Optional[String] = None
    SecretsManagerSecretId: Optional[String] = None
    ServerName: Optional[String] = None
    ServerTimezone: Optional[String] = None
    TargetDbType_1: Optional[TargetDbType] = Field(None, alias='TargetDbType')
    Username: Optional[String] = None


class IBMDb2Settings(BaseModel):
    CurrentLsn: Optional[String] = None
    DatabaseName: Optional[String] = None
    MaxKBytesPerRead: Optional[IntegerOptional] = None
    Password: Optional[SecretString] = None
    Port: Optional[IntegerOptional] = None
    SecretsManagerAccessRoleArn: Optional[String] = None
    SecretsManagerSecretId: Optional[String] = None
    ServerName: Optional[String] = None
    SetDataCaptureChanges: Optional[BooleanOptional] = None
    Username: Optional[String] = None


class ImportCertificateMessage(BaseModel):
    CertificateIdentifier: String
    CertificatePem: Optional[SecretString] = None
    CertificateWallet_1: Optional[CertificateWallet] = Field(
        None, alias='CertificateWallet'
    )
    Tags: Optional[TagList] = None


class ImportCertificateResponse(BaseModel):
    Certificate_1: Optional[Certificate] = Field(None, alias='Certificate')


class IncludeTestList(RootModel[List[String]]):
    root: List[String]


class IndividualAssessmentNameList(RootModel[List[String]]):
    root: List[String]


class KafkaSettings(BaseModel):
    Broker: Optional[String] = None
    IncludeControlDetails: Optional[BooleanOptional] = None
    IncludeNullAndEmpty: Optional[BooleanOptional] = None
    IncludePartitionValue: Optional[BooleanOptional] = None
    IncludeTableAlterOperations: Optional[BooleanOptional] = None
    IncludeTransactionDetails: Optional[BooleanOptional] = None
    MessageFormat: Optional[MessageFormatValue] = None
    MessageMaxBytes: Optional[IntegerOptional] = None
    NoHexPrefix: Optional[BooleanOptional] = None
    PartitionIncludeSchemaTable: Optional[BooleanOptional] = None
    SaslMechanism: Optional[KafkaSaslMechanism] = None
    SaslPassword: Optional[SecretString] = None
    SaslUsername: Optional[String] = None
    SecurityProtocol: Optional[KafkaSecurityProtocol] = None
    SslCaCertificateArn: Optional[String] = None
    SslClientCertificateArn: Optional[String] = None
    SslClientKeyArn: Optional[String] = None
    SslClientKeyPassword: Optional[SecretString] = None
    Topic: Optional[String] = None


class KeyList(RootModel[List[String]]):
    root: List[String]


class KinesisSettings(BaseModel):
    IncludeControlDetails: Optional[BooleanOptional] = None
    IncludeNullAndEmpty: Optional[BooleanOptional] = None
    IncludePartitionValue: Optional[BooleanOptional] = None
    IncludeTableAlterOperations: Optional[BooleanOptional] = None
    IncludeTransactionDetails: Optional[BooleanOptional] = None
    MessageFormat: Optional[MessageFormatValue] = None
    NoHexPrefix: Optional[BooleanOptional] = None
    PartitionIncludeSchemaTable: Optional[BooleanOptional] = None
    ServiceAccessRoleArn: Optional[String] = None
    StreamArn: Optional[String] = None


class Limitation(BaseModel):
    DatabaseId: Optional[String] = None
    Description: Optional[String] = None
    EngineName: Optional[String] = None
    Impact: Optional[String] = None
    Name: Optional[String] = None
    Type: Optional[String] = None


class LimitationList(RootModel[List[Limitation]]):
    root: List[Limitation]


class ListTagsForResourceMessage(BaseModel):
    ResourceArn: Optional[String] = None
    ResourceArnList: Optional[ArnList] = None


class ListTagsForResourceResponse(BaseModel):
    TagList_1: Optional[TagList] = Field(None, alias='TagList')


class MicrosoftSQLServerSettings(BaseModel):
    BcpPacketSize: Optional[IntegerOptional] = None
    ControlTablesFileGroup: Optional[String] = None
    DatabaseName: Optional[String] = None
    ForceLobLookup: Optional[BooleanOptional] = None
    Password: Optional[SecretString] = None
    Port: Optional[IntegerOptional] = None
    QuerySingleAlwaysOnNode: Optional[BooleanOptional] = None
    ReadBackupOnly: Optional[BooleanOptional] = None
    SafeguardPolicy_1: Optional[SafeguardPolicy] = Field(None, alias='SafeguardPolicy')
    SecretsManagerAccessRoleArn: Optional[String] = None
    SecretsManagerSecretId: Optional[String] = None
    ServerName: Optional[String] = None
    TlogAccessMode_1: Optional[TlogAccessMode] = Field(None, alias='TlogAccessMode')
    TrimSpaceInChar: Optional[BooleanOptional] = None
    UseBcpFullLoad: Optional[BooleanOptional] = None
    UseThirdPartyBackupDevice: Optional[BooleanOptional] = None
    Username: Optional[String] = None


class ModifyEventSubscriptionMessage(BaseModel):
    Enabled: Optional[BooleanOptional] = None
    EventCategories: Optional[EventCategoriesList] = None
    SnsTopicArn: Optional[String] = None
    SourceType: Optional[String] = None
    SubscriptionName: String


class ModifyReplicationInstanceMessage(BaseModel):
    AllocatedStorage: Optional[IntegerOptional] = None
    AllowMajorVersionUpgrade: Optional[Boolean] = None
    ApplyImmediately: Optional[Boolean] = None
    AutoMinorVersionUpgrade: Optional[BooleanOptional] = None
    EngineVersion: Optional[String] = None
    MultiAZ: Optional[BooleanOptional] = None
    NetworkType: Optional[String] = None
    PreferredMaintenanceWindow: Optional[String] = None
    ReplicationInstanceArn: String
    ReplicationInstanceClass: Optional[String] = None
    ReplicationInstanceIdentifier: Optional[String] = None
    VpcSecurityGroupIds: Optional[VpcSecurityGroupIdList] = None


class ModifyReplicationSubnetGroupMessage(BaseModel):
    ReplicationSubnetGroupDescription: Optional[String] = None
    ReplicationSubnetGroupIdentifier: String
    SubnetIds: SubnetIdentifierList


class ModifyReplicationTaskMessage(BaseModel):
    CdcStartPosition: Optional[String] = None
    CdcStartTime: Optional[TStamp] = None
    CdcStopPosition: Optional[String] = None
    MigrationType: Optional[MigrationTypeValue] = None
    ReplicationTaskArn: String
    ReplicationTaskIdentifier: Optional[String] = None
    ReplicationTaskSettings: Optional[String] = None
    TableMappings: Optional[String] = None
    TaskData: Optional[String] = None


class MongoDbSettings(BaseModel):
    AuthMechanism: Optional[AuthMechanismValue] = None
    AuthSource: Optional[String] = None
    AuthType: Optional[AuthTypeValue] = None
    DatabaseName: Optional[String] = None
    DocsToInvestigate: Optional[String] = None
    ExtractDocId: Optional[String] = None
    KmsKeyId: Optional[String] = None
    NestingLevel: Optional[NestingLevelValue] = None
    Password: Optional[SecretString] = None
    Port: Optional[IntegerOptional] = None
    SecretsManagerAccessRoleArn: Optional[String] = None
    SecretsManagerSecretId: Optional[String] = None
    ServerName: Optional[String] = None
    Username: Optional[String] = None


class MoveReplicationTaskMessage(BaseModel):
    ReplicationTaskArn: String
    TargetReplicationInstanceArn: String


class MySQLSettings(BaseModel):
    AfterConnectScript: Optional[String] = None
    CleanSourceMetadataOnMismatch: Optional[BooleanOptional] = None
    DatabaseName: Optional[String] = None
    EventsPollInterval: Optional[IntegerOptional] = None
    MaxFileSize: Optional[IntegerOptional] = None
    ParallelLoadThreads: Optional[IntegerOptional] = None
    Password: Optional[SecretString] = None
    Port: Optional[IntegerOptional] = None
    SecretsManagerAccessRoleArn: Optional[String] = None
    SecretsManagerSecretId: Optional[String] = None
    ServerName: Optional[String] = None
    ServerTimezone: Optional[String] = None
    TargetDbType_1: Optional[TargetDbType] = Field(None, alias='TargetDbType')
    Username: Optional[String] = None


class NeptuneSettings(BaseModel):
    ErrorRetryDuration: Optional[IntegerOptional] = None
    IamAuthEnabled: Optional[BooleanOptional] = None
    MaxFileSize: Optional[IntegerOptional] = None
    MaxRetryCount: Optional[IntegerOptional] = None
    S3BucketFolder: String
    S3BucketName: String
    ServiceAccessRoleArn: Optional[String] = None


class OracleSettings(BaseModel):
    AccessAlternateDirectly: Optional[BooleanOptional] = None
    AddSupplementalLogging: Optional[BooleanOptional] = None
    AdditionalArchivedLogDestId: Optional[IntegerOptional] = None
    AllowSelectNestedTables: Optional[BooleanOptional] = None
    ArchivedLogDestId: Optional[IntegerOptional] = None
    ArchivedLogsOnly: Optional[BooleanOptional] = None
    AsmPassword: Optional[SecretString] = None
    AsmServer: Optional[String] = None
    AsmUser: Optional[String] = None
    CharLengthSemantics_1: Optional[CharLengthSemantics] = Field(
        None, alias='CharLengthSemantics'
    )
    ConvertTimestampWithZoneToUTC: Optional[BooleanOptional] = None
    DatabaseName: Optional[String] = None
    DirectPathNoLog: Optional[BooleanOptional] = None
    DirectPathParallelLoad: Optional[BooleanOptional] = None
    EnableHomogenousTablespace: Optional[BooleanOptional] = None
    ExtraArchivedLogDestIds: Optional[IntegerList] = None
    FailTasksOnLobTruncation: Optional[BooleanOptional] = None
    NumberDatatypeScale: Optional[IntegerOptional] = None
    OraclePathPrefix: Optional[String] = None
    ParallelAsmReadThreads: Optional[IntegerOptional] = None
    Password: Optional[SecretString] = None
    Port: Optional[IntegerOptional] = None
    ReadAheadBlocks: Optional[IntegerOptional] = None
    ReadTableSpaceName: Optional[BooleanOptional] = None
    ReplacePathPrefix: Optional[BooleanOptional] = None
    RetryInterval: Optional[IntegerOptional] = None
    SecretsManagerAccessRoleArn: Optional[String] = None
    SecretsManagerOracleAsmAccessRoleArn: Optional[String] = None
    SecretsManagerOracleAsmSecretId: Optional[String] = None
    SecretsManagerSecretId: Optional[String] = None
    SecurityDbEncryption: Optional[SecretString] = None
    SecurityDbEncryptionName: Optional[String] = None
    ServerName: Optional[String] = None
    SpatialDataOptionToGeoJsonFunctionName: Optional[String] = None
    StandbyDelayTime: Optional[IntegerOptional] = None
    TrimSpaceInChar: Optional[BooleanOptional] = None
    UseAlternateFolderForOnline: Optional[BooleanOptional] = None
    UseBFile: Optional[BooleanOptional] = None
    UseDirectPathFullLoad: Optional[BooleanOptional] = None
    UseLogminerReader: Optional[BooleanOptional] = None
    UsePathPrefix: Optional[String] = None
    Username: Optional[String] = None


class OrderableReplicationInstance(BaseModel):
    AvailabilityZones: Optional[AvailabilityZonesList] = None
    DefaultAllocatedStorage: Optional[Integer] = None
    EngineVersion: Optional[String] = None
    IncludedAllocatedStorage: Optional[Integer] = None
    MaxAllocatedStorage: Optional[Integer] = None
    MinAllocatedStorage: Optional[Integer] = None
    ReleaseStatus: Optional[ReleaseStatusValues] = None
    ReplicationInstanceClass: Optional[String] = None
    StorageType: Optional[String] = None


class OrderableReplicationInstanceList(RootModel[List[OrderableReplicationInstance]]):
    root: List[OrderableReplicationInstance]


class PendingMaintenanceAction(BaseModel):
    Action: Optional[String] = None
    AutoAppliedAfterDate: Optional[TStamp] = None
    CurrentApplyDate: Optional[TStamp] = None
    Description: Optional[String] = None
    ForcedApplyDate: Optional[TStamp] = None
    OptInStatus: Optional[String] = None


class PendingMaintenanceActionDetails(RootModel[List[PendingMaintenanceAction]]):
    root: List[PendingMaintenanceAction]


class PostgreSQLSettings(BaseModel):
    AfterConnectScript: Optional[String] = None
    CaptureDdls: Optional[BooleanOptional] = None
    DatabaseName: Optional[String] = None
    DdlArtifactsSchema: Optional[String] = None
    ExecuteTimeout: Optional[IntegerOptional] = None
    FailTasksOnLobTruncation: Optional[BooleanOptional] = None
    HeartbeatEnable: Optional[BooleanOptional] = None
    HeartbeatFrequency: Optional[IntegerOptional] = None
    HeartbeatSchema: Optional[String] = None
    MapBooleanAsBoolean: Optional[BooleanOptional] = None
    MaxFileSize: Optional[IntegerOptional] = None
    Password: Optional[SecretString] = None
    PluginName: Optional[PluginNameValue] = None
    Port: Optional[IntegerOptional] = None
    SecretsManagerAccessRoleArn: Optional[String] = None
    SecretsManagerSecretId: Optional[String] = None
    ServerName: Optional[String] = None
    SlotName: Optional[String] = None
    TrimSpaceInChar: Optional[BooleanOptional] = None
    Username: Optional[String] = None


class RdsConfiguration(BaseModel):
    DeploymentOption: Optional[String] = None
    EngineEdition: Optional[String] = None
    InstanceMemory: Optional[DoubleOptional] = None
    InstanceType: Optional[String] = None
    InstanceVcpu: Optional[DoubleOptional] = None
    StorageIops: Optional[IntegerOptional] = None
    StorageSize: Optional[IntegerOptional] = None
    StorageType: Optional[String] = None


class RdsRequirements(BaseModel):
    DeploymentOption: Optional[String] = None
    EngineEdition: Optional[String] = None
    InstanceMemory: Optional[DoubleOptional] = None
    InstanceVcpu: Optional[DoubleOptional] = None
    StorageIops: Optional[IntegerOptional] = None
    StorageSize: Optional[IntegerOptional] = None


class RebootReplicationInstanceMessage(BaseModel):
    ForceFailover: Optional[BooleanOptional] = None
    ForcePlannedFailover: Optional[BooleanOptional] = None
    ReplicationInstanceArn: String


class RecommendationSettings(BaseModel):
    InstanceSizingType: String
    WorkloadType: String


class RedisSettings(BaseModel):
    AuthPassword: Optional[SecretString] = None
    AuthType: Optional[RedisAuthTypeValue] = None
    AuthUserName: Optional[String] = None
    Port: Integer
    ServerName: String
    SslCaCertificateArn: Optional[String] = None
    SslSecurityProtocol: Optional[SslSecurityProtocolValue] = None


class RedshiftSettings(BaseModel):
    AcceptAnyDate: Optional[BooleanOptional] = None
    AfterConnectScript: Optional[String] = None
    BucketFolder: Optional[String] = None
    BucketName: Optional[String] = None
    CaseSensitiveNames: Optional[BooleanOptional] = None
    CompUpdate: Optional[BooleanOptional] = None
    ConnectionTimeout: Optional[IntegerOptional] = None
    DatabaseName: Optional[String] = None
    DateFormat: Optional[String] = None
    EmptyAsNull: Optional[BooleanOptional] = None
    EncryptionMode: Optional[EncryptionModeValue] = None
    ExplicitIds: Optional[BooleanOptional] = None
    FileTransferUploadStreams: Optional[IntegerOptional] = None
    LoadTimeout: Optional[IntegerOptional] = None
    MapBooleanAsBoolean: Optional[BooleanOptional] = None
    MaxFileSize: Optional[IntegerOptional] = None
    Password: Optional[SecretString] = None
    Port: Optional[IntegerOptional] = None
    RemoveQuotes: Optional[BooleanOptional] = None
    ReplaceChars: Optional[String] = None
    ReplaceInvalidChars: Optional[String] = None
    SecretsManagerAccessRoleArn: Optional[String] = None
    SecretsManagerSecretId: Optional[String] = None
    ServerName: Optional[String] = None
    ServerSideEncryptionKmsKeyId: Optional[String] = None
    ServiceAccessRoleArn: Optional[String] = None
    TimeFormat: Optional[String] = None
    TrimBlanks: Optional[BooleanOptional] = None
    TruncateColumns: Optional[BooleanOptional] = None
    Username: Optional[String] = None
    WriteBufferSize: Optional[IntegerOptional] = None


class RefreshSchemasMessage(BaseModel):
    EndpointArn: String
    ReplicationInstanceArn: String


class RefreshSchemasStatus(BaseModel):
    EndpointArn: Optional[String] = None
    LastFailureMessage: Optional[String] = None
    LastRefreshDate: Optional[TStamp] = None
    ReplicationInstanceArn: Optional[String] = None
    Status: Optional[RefreshSchemasStatusTypeValue] = None


class ReloadTablesResponse(BaseModel):
    ReplicationTaskArn: Optional[String] = None


class RemoveTagsFromResourceMessage(BaseModel):
    ResourceArn: String
    TagKeys: KeyList


class ReplicationInstanceIpv6AddressList(RootModel[List[String]]):
    root: List[String]


class ReplicationInstancePrivateIpAddressList(RootModel[List[String]]):
    root: List[String]


class ReplicationInstancePublicIpAddressList(RootModel[List[String]]):
    root: List[String]


class ReplicationInstanceTaskLog(BaseModel):
    ReplicationInstanceTaskLogSize: Optional[Long] = None
    ReplicationTaskArn: Optional[String] = None
    ReplicationTaskName: Optional[String] = None


class ReplicationInstanceTaskLogsList(RootModel[List[ReplicationInstanceTaskLog]]):
    root: List[ReplicationInstanceTaskLog]


class ReplicationPendingModifiedValues(BaseModel):
    AllocatedStorage: Optional[IntegerOptional] = None
    EngineVersion: Optional[String] = None
    MultiAZ: Optional[BooleanOptional] = None
    NetworkType: Optional[String] = None
    ReplicationInstanceClass: Optional[String] = None


class ReplicationTaskAssessmentResult(BaseModel):
    AssessmentResults: Optional[String] = None
    AssessmentResultsFile: Optional[String] = None
    AssessmentStatus: Optional[String] = None
    ReplicationTaskArn: Optional[String] = None
    ReplicationTaskIdentifier: Optional[String] = None
    ReplicationTaskLastAssessmentDate: Optional[TStamp] = None
    S3ObjectUrl: Optional[String] = None


class ReplicationTaskAssessmentResultList(
    RootModel[List[ReplicationTaskAssessmentResult]]
):
    root: List[ReplicationTaskAssessmentResult]


class ReplicationTaskAssessmentRun(BaseModel):
    AssessmentProgress: Optional[ReplicationTaskAssessmentRunProgress] = None
    AssessmentRunName: Optional[String] = None
    LastFailureMessage: Optional[String] = None
    ReplicationTaskArn: Optional[String] = None
    ReplicationTaskAssessmentRunArn: Optional[String] = None
    ReplicationTaskAssessmentRunCreationDate: Optional[TStamp] = None
    ResultEncryptionMode: Optional[String] = None
    ResultKmsKeyArn: Optional[String] = None
    ResultLocationBucket: Optional[String] = None
    ResultLocationFolder: Optional[String] = None
    ServiceAccessRoleArn: Optional[String] = None
    Status: Optional[String] = None


class ReplicationTaskAssessmentRunList(RootModel[List[ReplicationTaskAssessmentRun]]):
    root: List[ReplicationTaskAssessmentRun]


class ReplicationTaskIndividualAssessment(BaseModel):
    IndividualAssessmentName: Optional[String] = None
    ReplicationTaskAssessmentRunArn: Optional[String] = None
    ReplicationTaskIndividualAssessmentArn: Optional[String] = None
    ReplicationTaskIndividualAssessmentStartDate: Optional[TStamp] = None
    Status: Optional[String] = None


class ReplicationTaskIndividualAssessmentList(
    RootModel[List[ReplicationTaskIndividualAssessment]]
):
    root: List[ReplicationTaskIndividualAssessment]


class ReplicationTaskStats(BaseModel):
    ElapsedTimeMillis: Optional[Long] = None
    FreshStartDate: Optional[TStamp] = None
    FullLoadFinishDate: Optional[TStamp] = None
    FullLoadProgressPercent: Optional[Integer] = None
    FullLoadStartDate: Optional[TStamp] = None
    StartDate: Optional[TStamp] = None
    StopDate: Optional[TStamp] = None
    TablesErrored: Optional[Integer] = None
    TablesLoaded: Optional[Integer] = None
    TablesLoading: Optional[Integer] = None
    TablesQueued: Optional[Integer] = None


class ResourcePendingMaintenanceActions(BaseModel):
    PendingMaintenanceActionDetails_1: Optional[PendingMaintenanceActionDetails] = (
        Field(None, alias='PendingMaintenanceActionDetails')
    )
    ResourceIdentifier: Optional[String] = None


class RunFleetAdvisorLsaAnalysisResponse(BaseModel):
    LsaAnalysisId: Optional[String] = None
    Status: Optional[String] = None


class S3Settings(BaseModel):
    AddColumnName: Optional[BooleanOptional] = None
    AddTrailingPaddingCharacter: Optional[BooleanOptional] = None
    BucketFolder: Optional[String] = None
    BucketName: Optional[String] = None
    CannedAclForObjects: Optional[CannedAclForObjectsValue] = None
    CdcInsertsAndUpdates: Optional[BooleanOptional] = None
    CdcInsertsOnly: Optional[BooleanOptional] = None
    CdcMaxBatchInterval: Optional[IntegerOptional] = None
    CdcMinFileSize: Optional[IntegerOptional] = None
    CdcPath: Optional[String] = None
    CompressionType: Optional[CompressionTypeValue] = None
    CsvDelimiter: Optional[String] = None
    CsvNoSupValue: Optional[String] = None
    CsvNullValue: Optional[String] = None
    CsvRowDelimiter: Optional[String] = None
    DataFormat: Optional[DataFormatValue] = None
    DataPageSize: Optional[IntegerOptional] = None
    DatePartitionDelimiter: Optional[DatePartitionDelimiterValue] = None
    DatePartitionEnabled: Optional[BooleanOptional] = None
    DatePartitionSequence: Optional[DatePartitionSequenceValue] = None
    DatePartitionTimezone: Optional[String] = None
    DictPageSizeLimit: Optional[IntegerOptional] = None
    EnableStatistics: Optional[BooleanOptional] = None
    EncodingType: Optional[EncodingTypeValue] = None
    EncryptionMode: Optional[EncryptionModeValue] = None
    ExpectedBucketOwner: Optional[String] = None
    ExternalTableDefinition: Optional[String] = None
    GlueCatalogGeneration: Optional[BooleanOptional] = None
    IgnoreHeaderRows: Optional[IntegerOptional] = None
    IncludeOpForFullLoad: Optional[BooleanOptional] = None
    MaxFileSize: Optional[IntegerOptional] = None
    ParquetTimestampInMillisecond: Optional[BooleanOptional] = None
    ParquetVersion: Optional[ParquetVersionValue] = None
    PreserveTransactions: Optional[BooleanOptional] = None
    Rfc4180: Optional[BooleanOptional] = None
    RowGroupLength: Optional[IntegerOptional] = None
    ServerSideEncryptionKmsKeyId: Optional[String] = None
    ServiceAccessRoleArn: Optional[String] = None
    TimestampColumnName: Optional[String] = None
    UseCsvNoSupValue: Optional[BooleanOptional] = None
    UseTaskStartTimeForFullLoadTimestamp: Optional[BooleanOptional] = None


class SchemaList(RootModel[List[String]]):
    root: List[String]


class SchemaShortInfoResponse(BaseModel):
    DatabaseId: Optional[String] = None
    DatabaseIpAddress: Optional[String] = None
    DatabaseName: Optional[String] = None
    SchemaId: Optional[String] = None
    SchemaName: Optional[String] = None


class ServerShortInfoResponse(BaseModel):
    IpAddress: Optional[String] = None
    ServerId: Optional[String] = None
    ServerName: Optional[String] = None


class SourceIdsList(RootModel[List[String]]):
    root: List[String]


class StartRecommendationsRequest(BaseModel):
    DatabaseId: String
    Settings: RecommendationSettings


class StartRecommendationsRequestEntry(BaseModel):
    DatabaseId: String
    Settings: RecommendationSettings


class StartRecommendationsRequestEntryList(
    RootModel[List[StartRecommendationsRequestEntry]]
):
    root: List[StartRecommendationsRequestEntry]


class StartReplicationTaskAssessmentMessage(BaseModel):
    ReplicationTaskArn: String


class StartReplicationTaskAssessmentRunMessage(BaseModel):
    AssessmentRunName: String
    Exclude: Optional[ExcludeTestList] = None
    IncludeOnly: Optional[IncludeTestList] = None
    ReplicationTaskArn: String
    ResultEncryptionMode: Optional[String] = None
    ResultKmsKeyArn: Optional[String] = None
    ResultLocationBucket: String
    ResultLocationFolder: Optional[String] = None
    ServiceAccessRoleArn: String


class StartReplicationTaskAssessmentRunResponse(BaseModel):
    ReplicationTaskAssessmentRun_1: Optional[ReplicationTaskAssessmentRun] = Field(
        None, alias='ReplicationTaskAssessmentRun'
    )


class StartReplicationTaskMessage(BaseModel):
    CdcStartPosition: Optional[String] = None
    CdcStartTime: Optional[TStamp] = None
    CdcStopPosition: Optional[String] = None
    ReplicationTaskArn: String
    StartReplicationTaskType: StartReplicationTaskTypeValue


class StopReplicationTaskMessage(BaseModel):
    ReplicationTaskArn: String


class Subnet(BaseModel):
    SubnetAvailabilityZone: Optional[AvailabilityZone] = None
    SubnetIdentifier: Optional[String] = None
    SubnetStatus: Optional[String] = None


class SubnetList(RootModel[List[Subnet]]):
    root: List[Subnet]


class TableListToReload(RootModel[List[TableToReload]]):
    root: List[TableToReload]


class TestConnectionResponse(BaseModel):
    Connection_1: Optional[Connection] = Field(None, alias='Connection')


class ApplyPendingMaintenanceActionResponse(BaseModel):
    ResourcePendingMaintenanceActions_1: Optional[ResourcePendingMaintenanceActions] = (
        Field(None, alias='ResourcePendingMaintenanceActions')
    )


class BatchStartRecommendationsRequest(BaseModel):
    Data: Optional[StartRecommendationsRequestEntryList] = None


class CancelReplicationTaskAssessmentRunResponse(BaseModel):
    ReplicationTaskAssessmentRun_1: Optional[ReplicationTaskAssessmentRun] = Field(
        None, alias='ReplicationTaskAssessmentRun'
    )


class CreateEndpointMessage(BaseModel):
    CertificateArn: Optional[String] = None
    DatabaseName: Optional[String] = None
    DmsTransferSettings_1: Optional[DmsTransferSettings] = Field(
        None, alias='DmsTransferSettings'
    )
    DocDbSettings_1: Optional[DocDbSettings] = Field(None, alias='DocDbSettings')
    DynamoDbSettings_1: Optional[DynamoDbSettings] = Field(
        None, alias='DynamoDbSettings'
    )
    ElasticsearchSettings_1: Optional[ElasticsearchSettings] = Field(
        None, alias='ElasticsearchSettings'
    )
    EndpointIdentifier: String
    EndpointType: ReplicationEndpointTypeValue
    EngineName: String
    ExternalTableDefinition: Optional[String] = None
    ExtraConnectionAttributes: Optional[String] = None
    GcpMySQLSettings_1: Optional[GcpMySQLSettings] = Field(
        None, alias='GcpMySQLSettings'
    )
    IBMDb2Settings_1: Optional[IBMDb2Settings] = Field(None, alias='IBMDb2Settings')
    KafkaSettings_1: Optional[KafkaSettings] = Field(None, alias='KafkaSettings')
    KinesisSettings_1: Optional[KinesisSettings] = Field(None, alias='KinesisSettings')
    KmsKeyId: Optional[String] = None
    MicrosoftSQLServerSettings_1: Optional[MicrosoftSQLServerSettings] = Field(
        None, alias='MicrosoftSQLServerSettings'
    )
    MongoDbSettings_1: Optional[MongoDbSettings] = Field(None, alias='MongoDbSettings')
    MySQLSettings_1: Optional[MySQLSettings] = Field(None, alias='MySQLSettings')
    NeptuneSettings_1: Optional[NeptuneSettings] = Field(None, alias='NeptuneSettings')
    OracleSettings_1: Optional[OracleSettings] = Field(None, alias='OracleSettings')
    Password: Optional[SecretString] = None
    Port: Optional[IntegerOptional] = None
    PostgreSQLSettings_1: Optional[PostgreSQLSettings] = Field(
        None, alias='PostgreSQLSettings'
    )
    RedisSettings_1: Optional[RedisSettings] = Field(None, alias='RedisSettings')
    RedshiftSettings_1: Optional[RedshiftSettings] = Field(
        None, alias='RedshiftSettings'
    )
    ResourceIdentifier: Optional[String] = None
    S3Settings_1: Optional[S3Settings] = Field(None, alias='S3Settings')
    ServerName: Optional[String] = None
    ServiceAccessRoleArn: Optional[String] = None
    SslMode: Optional[DmsSslModeValue] = None
    SybaseSettings_1: Optional[SybaseSettings] = Field(None, alias='SybaseSettings')
    Tags: Optional[TagList] = None
    Username: Optional[String] = None


class CreateEventSubscriptionMessage(BaseModel):
    Enabled: Optional[BooleanOptional] = None
    EventCategories: Optional[EventCategoriesList] = None
    SnsTopicArn: String
    SourceIds: Optional[SourceIdsList] = None
    SourceType: Optional[String] = None
    SubscriptionName: String
    Tags: Optional[TagList] = None


class DatabaseResponse(BaseModel):
    Collectors: Optional[CollectorsList] = None
    DatabaseId: Optional[String] = None
    DatabaseName: Optional[String] = None
    IpAddress: Optional[String] = None
    NumberOfSchemas: Optional[LongOptional] = None
    Server: Optional[ServerShortInfoResponse] = None
    SoftwareDetails: Optional[DatabaseInstanceSoftwareDetailsResponse] = None


class DeleteReplicationTaskAssessmentRunResponse(BaseModel):
    ReplicationTaskAssessmentRun_1: Optional[ReplicationTaskAssessmentRun] = Field(
        None, alias='ReplicationTaskAssessmentRun'
    )


class DescribeApplicableIndividualAssessmentsResponse(BaseModel):
    IndividualAssessmentNames: Optional[IndividualAssessmentNameList] = None
    Marker: Optional[String] = None


class DescribeEventCategoriesResponse(BaseModel):
    EventCategoryGroupList_1: Optional[EventCategoryGroupList] = Field(
        None, alias='EventCategoryGroupList'
    )


class DescribeFleetAdvisorLsaAnalysisResponse(BaseModel):
    Analysis: Optional[FleetAdvisorLsaAnalysisResponseList] = None
    NextToken: Optional[String] = None


class DescribeOrderableReplicationInstancesResponse(BaseModel):
    Marker: Optional[String] = None
    OrderableReplicationInstances: Optional[OrderableReplicationInstanceList] = None


class DescribeRecommendationLimitationsResponse(BaseModel):
    Limitations: Optional[LimitationList] = None
    NextToken: Optional[String] = None


class DescribeRefreshSchemasStatusResponse(BaseModel):
    RefreshSchemasStatus_1: Optional[RefreshSchemasStatus] = Field(
        None, alias='RefreshSchemasStatus'
    )


class DescribeReplicationInstanceTaskLogsResponse(BaseModel):
    Marker: Optional[String] = None
    ReplicationInstanceArn: Optional[String] = None
    ReplicationInstanceTaskLogs: Optional[ReplicationInstanceTaskLogsList] = None


class DescribeReplicationTaskAssessmentResultsResponse(BaseModel):
    BucketName: Optional[String] = None
    Marker: Optional[String] = None
    ReplicationTaskAssessmentResults: Optional[ReplicationTaskAssessmentResultList] = (
        None
    )


class DescribeReplicationTaskAssessmentRunsResponse(BaseModel):
    Marker: Optional[String] = None
    ReplicationTaskAssessmentRuns: Optional[ReplicationTaskAssessmentRunList] = None


class DescribeReplicationTaskIndividualAssessmentsResponse(BaseModel):
    Marker: Optional[String] = None
    ReplicationTaskIndividualAssessments: Optional[
        ReplicationTaskIndividualAssessmentList
    ] = None


class DescribeSchemasResponse(BaseModel):
    Marker: Optional[String] = None
    Schemas: Optional[SchemaList] = None


class Endpoint(BaseModel):
    CertificateArn: Optional[String] = None
    DatabaseName: Optional[String] = None
    DmsTransferSettings_1: Optional[DmsTransferSettings] = Field(
        None, alias='DmsTransferSettings'
    )
    DocDbSettings_1: Optional[DocDbSettings] = Field(None, alias='DocDbSettings')
    DynamoDbSettings_1: Optional[DynamoDbSettings] = Field(
        None, alias='DynamoDbSettings'
    )
    ElasticsearchSettings_1: Optional[ElasticsearchSettings] = Field(
        None, alias='ElasticsearchSettings'
    )
    EndpointArn: Optional[String] = None
    EndpointIdentifier: Optional[String] = None
    EndpointType: Optional[ReplicationEndpointTypeValue] = None
    EngineDisplayName: Optional[String] = None
    EngineName: Optional[String] = None
    ExternalId: Optional[String] = None
    ExternalTableDefinition: Optional[String] = None
    ExtraConnectionAttributes: Optional[String] = None
    GcpMySQLSettings_1: Optional[GcpMySQLSettings] = Field(
        None, alias='GcpMySQLSettings'
    )
    IBMDb2Settings_1: Optional[IBMDb2Settings] = Field(None, alias='IBMDb2Settings')
    KafkaSettings_1: Optional[KafkaSettings] = Field(None, alias='KafkaSettings')
    KinesisSettings_1: Optional[KinesisSettings] = Field(None, alias='KinesisSettings')
    KmsKeyId: Optional[String] = None
    MicrosoftSQLServerSettings_1: Optional[MicrosoftSQLServerSettings] = Field(
        None, alias='MicrosoftSQLServerSettings'
    )
    MongoDbSettings_1: Optional[MongoDbSettings] = Field(None, alias='MongoDbSettings')
    MySQLSettings_1: Optional[MySQLSettings] = Field(None, alias='MySQLSettings')
    NeptuneSettings_1: Optional[NeptuneSettings] = Field(None, alias='NeptuneSettings')
    OracleSettings_1: Optional[OracleSettings] = Field(None, alias='OracleSettings')
    Port: Optional[IntegerOptional] = None
    PostgreSQLSettings_1: Optional[PostgreSQLSettings] = Field(
        None, alias='PostgreSQLSettings'
    )
    RedisSettings_1: Optional[RedisSettings] = Field(None, alias='RedisSettings')
    RedshiftSettings_1: Optional[RedshiftSettings] = Field(
        None, alias='RedshiftSettings'
    )
    S3Settings_1: Optional[S3Settings] = Field(None, alias='S3Settings')
    ServerName: Optional[String] = None
    ServiceAccessRoleArn: Optional[String] = None
    SslMode: Optional[DmsSslModeValue] = None
    Status: Optional[String] = None
    SybaseSettings_1: Optional[SybaseSettings] = Field(None, alias='SybaseSettings')
    Username: Optional[String] = None


class EndpointList(RootModel[List[Endpoint]]):
    root: List[Endpoint]


class EndpointSetting(BaseModel):
    Applicability: Optional[String] = None
    DefaultValue: Optional[String] = None
    EnumValues: Optional[EndpointSettingEnumValues] = None
    IntValueMax: Optional[IntegerOptional] = None
    IntValueMin: Optional[IntegerOptional] = None
    Name: Optional[String] = None
    Sensitive: Optional[BooleanOptional] = None
    Type: Optional[EndpointSettingTypeValue] = None
    Units: Optional[String] = None


class EndpointSettingsList(RootModel[List[EndpointSetting]]):
    root: List[EndpointSetting]


class Event(BaseModel):
    Date: Optional[TStamp] = None
    EventCategories: Optional[EventCategoriesList] = None
    Message: Optional[String] = None
    SourceIdentifier: Optional[String] = None
    SourceType_1: Optional[SourceType] = Field(None, alias='SourceType')


class EventList(RootModel[List[Event]]):
    root: List[Event]


class EventSubscription(BaseModel):
    CustSubscriptionId: Optional[String] = None
    CustomerAwsId: Optional[String] = None
    Enabled: Optional[Boolean] = None
    EventCategoriesList_1: Optional[EventCategoriesList] = Field(
        None, alias='EventCategoriesList'
    )
    SnsTopicArn: Optional[String] = None
    SourceIdsList_1: Optional[SourceIdsList] = Field(None, alias='SourceIdsList')
    SourceType: Optional[String] = None
    Status: Optional[String] = None
    SubscriptionCreationTime: Optional[String] = None


class EventSubscriptionsList(RootModel[List[EventSubscription]]):
    root: List[EventSubscription]


class Filter(BaseModel):
    Name: String
    Values: FilterValueList


class FilterList(RootModel[List[Filter]]):
    root: List[Filter]


class FleetAdvisorSchemaObjectList(RootModel[List[FleetAdvisorSchemaObjectResponse]]):
    root: List[FleetAdvisorSchemaObjectResponse]


class ModifyEndpointMessage(BaseModel):
    CertificateArn: Optional[String] = None
    DatabaseName: Optional[String] = None
    DmsTransferSettings_1: Optional[DmsTransferSettings] = Field(
        None, alias='DmsTransferSettings'
    )
    DocDbSettings_1: Optional[DocDbSettings] = Field(None, alias='DocDbSettings')
    DynamoDbSettings_1: Optional[DynamoDbSettings] = Field(
        None, alias='DynamoDbSettings'
    )
    ElasticsearchSettings_1: Optional[ElasticsearchSettings] = Field(
        None, alias='ElasticsearchSettings'
    )
    EndpointArn: String
    EndpointIdentifier: Optional[String] = None
    EndpointType: Optional[ReplicationEndpointTypeValue] = None
    EngineName: Optional[String] = None
    ExactSettings: Optional[BooleanOptional] = None
    ExternalTableDefinition: Optional[String] = None
    ExtraConnectionAttributes: Optional[String] = None
    GcpMySQLSettings_1: Optional[GcpMySQLSettings] = Field(
        None, alias='GcpMySQLSettings'
    )
    IBMDb2Settings_1: Optional[IBMDb2Settings] = Field(None, alias='IBMDb2Settings')
    KafkaSettings_1: Optional[KafkaSettings] = Field(None, alias='KafkaSettings')
    KinesisSettings_1: Optional[KinesisSettings] = Field(None, alias='KinesisSettings')
    MicrosoftSQLServerSettings_1: Optional[MicrosoftSQLServerSettings] = Field(
        None, alias='MicrosoftSQLServerSettings'
    )
    MongoDbSettings_1: Optional[MongoDbSettings] = Field(None, alias='MongoDbSettings')
    MySQLSettings_1: Optional[MySQLSettings] = Field(None, alias='MySQLSettings')
    NeptuneSettings_1: Optional[NeptuneSettings] = Field(None, alias='NeptuneSettings')
    OracleSettings_1: Optional[OracleSettings] = Field(None, alias='OracleSettings')
    Password: Optional[SecretString] = None
    Port: Optional[IntegerOptional] = None
    PostgreSQLSettings_1: Optional[PostgreSQLSettings] = Field(
        None, alias='PostgreSQLSettings'
    )
    RedisSettings_1: Optional[RedisSettings] = Field(None, alias='RedisSettings')
    RedshiftSettings_1: Optional[RedshiftSettings] = Field(
        None, alias='RedshiftSettings'
    )
    S3Settings_1: Optional[S3Settings] = Field(None, alias='S3Settings')
    ServerName: Optional[String] = None
    ServiceAccessRoleArn: Optional[String] = None
    SslMode: Optional[DmsSslModeValue] = None
    SybaseSettings_1: Optional[SybaseSettings] = Field(None, alias='SybaseSettings')
    Username: Optional[String] = None


class ModifyEndpointResponse(BaseModel):
    Endpoint_1: Optional[Endpoint] = Field(None, alias='Endpoint')


class ModifyEventSubscriptionResponse(BaseModel):
    EventSubscription_1: Optional[EventSubscription] = Field(
        None, alias='EventSubscription'
    )


class PendingMaintenanceActions(RootModel[List[ResourcePendingMaintenanceActions]]):
    root: List[ResourcePendingMaintenanceActions]


class RdsRecommendation(BaseModel):
    RequirementsToTarget: Optional[RdsRequirements] = None
    TargetConfiguration: Optional[RdsConfiguration] = None


class RecommendationData(BaseModel):
    RdsEngine: Optional[RdsRecommendation] = None


class RefreshSchemasResponse(BaseModel):
    RefreshSchemasStatus_1: Optional[RefreshSchemasStatus] = Field(
        None, alias='RefreshSchemasStatus'
    )


class ReloadTablesMessage(BaseModel):
    ReloadOption: Optional[ReloadOptionValue] = None
    ReplicationTaskArn: String
    TablesToReload: TableListToReload


class ReplicationSubnetGroup(BaseModel):
    ReplicationSubnetGroupDescription: Optional[String] = None
    ReplicationSubnetGroupIdentifier: Optional[String] = None
    SubnetGroupStatus: Optional[String] = None
    Subnets: Optional[SubnetList] = None
    SupportedNetworkTypes: Optional[StringList] = None
    VpcId: Optional[String] = None


class ReplicationSubnetGroups(RootModel[List[ReplicationSubnetGroup]]):
    root: List[ReplicationSubnetGroup]


class ReplicationTask(BaseModel):
    CdcStartPosition: Optional[String] = None
    CdcStopPosition: Optional[String] = None
    LastFailureMessage: Optional[String] = None
    MigrationType: Optional[MigrationTypeValue] = None
    RecoveryCheckpoint: Optional[String] = None
    ReplicationInstanceArn: Optional[String] = None
    ReplicationTaskArn: Optional[String] = None
    ReplicationTaskCreationDate: Optional[TStamp] = None
    ReplicationTaskIdentifier: Optional[String] = None
    ReplicationTaskSettings: Optional[String] = None
    ReplicationTaskStartDate: Optional[TStamp] = None
    ReplicationTaskStats_1: Optional[ReplicationTaskStats] = Field(
        None, alias='ReplicationTaskStats'
    )
    SourceEndpointArn: Optional[String] = None
    Status: Optional[String] = None
    StopReason: Optional[String] = None
    TableMappings: Optional[String] = None
    TargetEndpointArn: Optional[String] = None
    TargetReplicationInstanceArn: Optional[String] = None
    TaskData: Optional[String] = None


class ReplicationTaskList(RootModel[List[ReplicationTask]]):
    root: List[ReplicationTask]


class SchemaResponse(BaseModel):
    CodeLineCount: Optional[LongOptional] = None
    CodeSize: Optional[LongOptional] = None
    Complexity: Optional[String] = None
    DatabaseInstance: Optional[DatabaseShortInfoResponse] = None
    OriginalSchema: Optional[SchemaShortInfoResponse] = None
    SchemaId: Optional[String] = None
    SchemaName: Optional[String] = None
    Server: Optional[ServerShortInfoResponse] = None
    Similarity: Optional[DoubleOptional] = None


class StartReplicationTaskAssessmentResponse(BaseModel):
    ReplicationTask_1: Optional[ReplicationTask] = Field(None, alias='ReplicationTask')


class StartReplicationTaskResponse(BaseModel):
    ReplicationTask_1: Optional[ReplicationTask] = Field(None, alias='ReplicationTask')


class StopReplicationTaskResponse(BaseModel):
    ReplicationTask_1: Optional[ReplicationTask] = Field(None, alias='ReplicationTask')


class CreateEndpointResponse(BaseModel):
    Endpoint_1: Optional[Endpoint] = Field(None, alias='Endpoint')


class CreateEventSubscriptionResponse(BaseModel):
    EventSubscription_1: Optional[EventSubscription] = Field(
        None, alias='EventSubscription'
    )


class CreateReplicationSubnetGroupResponse(BaseModel):
    ReplicationSubnetGroup_1: Optional[ReplicationSubnetGroup] = Field(
        None, alias='ReplicationSubnetGroup'
    )


class CreateReplicationTaskResponse(BaseModel):
    ReplicationTask_1: Optional[ReplicationTask] = Field(None, alias='ReplicationTask')


class DatabaseList(RootModel[List[DatabaseResponse]]):
    root: List[DatabaseResponse]


class DeleteEndpointResponse(BaseModel):
    Endpoint_1: Optional[Endpoint] = Field(None, alias='Endpoint')


class DeleteEventSubscriptionResponse(BaseModel):
    EventSubscription_1: Optional[EventSubscription] = Field(
        None, alias='EventSubscription'
    )


class DeleteReplicationTaskResponse(BaseModel):
    ReplicationTask_1: Optional[ReplicationTask] = Field(None, alias='ReplicationTask')


class DescribeCertificatesMessage(BaseModel):
    Filters: Optional[FilterList] = None
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None


class DescribeConnectionsMessage(BaseModel):
    Filters: Optional[FilterList] = None
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None


class DescribeEndpointSettingsResponse(BaseModel):
    EndpointSettings: Optional[EndpointSettingsList] = None
    Marker: Optional[String] = None


class DescribeEndpointTypesMessage(BaseModel):
    Filters: Optional[FilterList] = None
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None


class DescribeEndpointsMessage(BaseModel):
    Filters: Optional[FilterList] = None
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None


class DescribeEndpointsResponse(BaseModel):
    Endpoints: Optional[EndpointList] = None
    Marker: Optional[String] = None


class DescribeEventCategoriesMessage(BaseModel):
    Filters: Optional[FilterList] = None
    SourceType: Optional[String] = None


class DescribeEventSubscriptionsMessage(BaseModel):
    Filters: Optional[FilterList] = None
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None
    SubscriptionName: Optional[String] = None


class DescribeEventSubscriptionsResponse(BaseModel):
    EventSubscriptionsList_1: Optional[EventSubscriptionsList] = Field(
        None, alias='EventSubscriptionsList'
    )
    Marker: Optional[String] = None


class DescribeEventsMessage(BaseModel):
    Duration: Optional[IntegerOptional] = None
    EndTime: Optional[TStamp] = None
    EventCategories: Optional[EventCategoriesList] = None
    Filters: Optional[FilterList] = None
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None
    SourceIdentifier: Optional[String] = None
    SourceType_1: Optional[SourceType] = Field(None, alias='SourceType')
    StartTime: Optional[TStamp] = None


class DescribeEventsResponse(BaseModel):
    Events: Optional[EventList] = None
    Marker: Optional[String] = None


class DescribeFleetAdvisorCollectorsRequest(BaseModel):
    Filters: Optional[FilterList] = None
    MaxRecords: Optional[IntegerOptional] = None
    NextToken: Optional[String] = None


class DescribeFleetAdvisorDatabasesRequest(BaseModel):
    Filters: Optional[FilterList] = None
    MaxRecords: Optional[IntegerOptional] = None
    NextToken: Optional[String] = None


class DescribeFleetAdvisorDatabasesResponse(BaseModel):
    Databases: Optional[DatabaseList] = None
    NextToken: Optional[String] = None


class DescribeFleetAdvisorSchemaObjectSummaryRequest(BaseModel):
    Filters: Optional[FilterList] = None
    MaxRecords: Optional[IntegerOptional] = None
    NextToken: Optional[String] = None


class DescribeFleetAdvisorSchemaObjectSummaryResponse(BaseModel):
    FleetAdvisorSchemaObjects: Optional[FleetAdvisorSchemaObjectList] = None
    NextToken: Optional[String] = None


class DescribeFleetAdvisorSchemasRequest(BaseModel):
    Filters: Optional[FilterList] = None
    MaxRecords: Optional[IntegerOptional] = None
    NextToken: Optional[String] = None


class DescribePendingMaintenanceActionsMessage(BaseModel):
    Filters: Optional[FilterList] = None
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None
    ReplicationInstanceArn: Optional[String] = None


class DescribePendingMaintenanceActionsResponse(BaseModel):
    Marker: Optional[String] = None
    PendingMaintenanceActions_1: Optional[PendingMaintenanceActions] = Field(
        None, alias='PendingMaintenanceActions'
    )


class DescribeRecommendationLimitationsRequest(BaseModel):
    Filters: Optional[FilterList] = None
    MaxRecords: Optional[IntegerOptional] = None
    NextToken: Optional[String] = None


class DescribeRecommendationsRequest(BaseModel):
    Filters: Optional[FilterList] = None
    MaxRecords: Optional[IntegerOptional] = None
    NextToken: Optional[String] = None


class DescribeReplicationInstancesMessage(BaseModel):
    Filters: Optional[FilterList] = None
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None


class DescribeReplicationSubnetGroupsMessage(BaseModel):
    Filters: Optional[FilterList] = None
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None


class DescribeReplicationSubnetGroupsResponse(BaseModel):
    Marker: Optional[String] = None
    ReplicationSubnetGroups_1: Optional[ReplicationSubnetGroups] = Field(
        None, alias='ReplicationSubnetGroups'
    )


class DescribeReplicationTaskAssessmentRunsMessage(BaseModel):
    Filters: Optional[FilterList] = None
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None


class DescribeReplicationTaskIndividualAssessmentsMessage(BaseModel):
    Filters: Optional[FilterList] = None
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None


class DescribeReplicationTasksMessage(BaseModel):
    Filters: Optional[FilterList] = None
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None
    WithoutSettings: Optional[BooleanOptional] = None


class DescribeReplicationTasksResponse(BaseModel):
    Marker: Optional[String] = None
    ReplicationTasks: Optional[ReplicationTaskList] = None


class DescribeTableStatisticsMessage(BaseModel):
    Filters: Optional[FilterList] = None
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None
    ReplicationTaskArn: String


class FleetAdvisorSchemaList(RootModel[List[SchemaResponse]]):
    root: List[SchemaResponse]


class ModifyReplicationSubnetGroupResponse(BaseModel):
    ReplicationSubnetGroup_1: Optional[ReplicationSubnetGroup] = Field(
        None, alias='ReplicationSubnetGroup'
    )


class ModifyReplicationTaskResponse(BaseModel):
    ReplicationTask_1: Optional[ReplicationTask] = Field(None, alias='ReplicationTask')


class MoveReplicationTaskResponse(BaseModel):
    ReplicationTask_1: Optional[ReplicationTask] = Field(None, alias='ReplicationTask')


class Recommendation(BaseModel):
    CreatedDate: Optional[String] = None
    Data: Optional[RecommendationData] = None
    DatabaseId: Optional[String] = None
    EngineName: Optional[String] = None
    Preferred: Optional[BooleanOptional] = None
    Settings: Optional[RecommendationSettings] = None
    Status: Optional[String] = None


class RecommendationList(RootModel[List[Recommendation]]):
    root: List[Recommendation]


class ReplicationInstance(BaseModel):
    AllocatedStorage: Optional[Integer] = None
    AutoMinorVersionUpgrade: Optional[Boolean] = None
    AvailabilityZone: Optional[String] = None
    DnsNameServers: Optional[String] = None
    EngineVersion: Optional[String] = None
    FreeUntil: Optional[TStamp] = None
    InstanceCreateTime: Optional[TStamp] = None
    KmsKeyId: Optional[String] = None
    MultiAZ: Optional[Boolean] = None
    NetworkType: Optional[String] = None
    PendingModifiedValues: Optional[ReplicationPendingModifiedValues] = None
    PreferredMaintenanceWindow: Optional[String] = None
    PubliclyAccessible: Optional[Boolean] = None
    ReplicationInstanceArn: Optional[String] = None
    ReplicationInstanceClass: Optional[String] = None
    ReplicationInstanceIdentifier: Optional[String] = None
    ReplicationInstanceIpv6Addresses: Optional[ReplicationInstanceIpv6AddressList] = (
        None
    )
    ReplicationInstancePrivateIpAddress: Optional[String] = None
    ReplicationInstancePrivateIpAddresses: Optional[
        ReplicationInstancePrivateIpAddressList
    ] = None
    ReplicationInstancePublicIpAddress: Optional[String] = None
    ReplicationInstancePublicIpAddresses: Optional[
        ReplicationInstancePublicIpAddressList
    ] = None
    ReplicationInstanceStatus: Optional[String] = None
    ReplicationSubnetGroup_1: Optional[ReplicationSubnetGroup] = Field(
        None, alias='ReplicationSubnetGroup'
    )
    SecondaryAvailabilityZone: Optional[String] = None
    VpcSecurityGroups: Optional[VpcSecurityGroupMembershipList] = None


class ReplicationInstanceList(RootModel[List[ReplicationInstance]]):
    root: List[ReplicationInstance]


class CreateReplicationInstanceResponse(BaseModel):
    ReplicationInstance_1: Optional[ReplicationInstance] = Field(
        None, alias='ReplicationInstance'
    )


class DeleteReplicationInstanceResponse(BaseModel):
    ReplicationInstance_1: Optional[ReplicationInstance] = Field(
        None, alias='ReplicationInstance'
    )


class DescribeFleetAdvisorSchemasResponse(BaseModel):
    FleetAdvisorSchemas: Optional[FleetAdvisorSchemaList] = None
    NextToken: Optional[String] = None


class DescribeRecommendationsResponse(BaseModel):
    NextToken: Optional[String] = None
    Recommendations: Optional[RecommendationList] = None


class DescribeReplicationInstancesResponse(BaseModel):
    Marker: Optional[String] = None
    ReplicationInstances: Optional[ReplicationInstanceList] = None


class ModifyReplicationInstanceResponse(BaseModel):
    ReplicationInstance_1: Optional[ReplicationInstance] = Field(
        None, alias='ReplicationInstance'
    )


class RebootReplicationInstanceResponse(BaseModel):
    ReplicationInstance_1: Optional[ReplicationInstance] = Field(
        None, alias='ReplicationInstance'
    )
